### ISSUE TITLE
Some mistakes about module.py

### ISSUE THREAD

**Issue by progressforever** [xy-guo/MVSNet_pytorch#1]
Sorry, I want to konw whether the 137 line is wrong. And how to change it. Thank you

**Comment by xy-guo** [comment]
It is trying to add two more dimensions for elementwise multiplication. I think there is no bug.

**Comment by progressforever** [comment]
> It is trying to add two more dimensions for elementwise multiplication. I think there is no bug.

Thank you for you reply, However,  the 
depth_values = depth_values.view(*depth_values.shape, 1, 1)
what is the * mean?

**Comment by xy-guo** [comment]
It is to unpack `depth_values.shape` as function arguments (you can refer to python tutorials for more information). It is the same as 

    depth_values = depth_values.view(depth_values.shape[0], depth_values.shape[1], 1, 1)  # only when len(depth_values.shape) == 2

**Comment by progressforever** [comment]
> It is to unpack `depth_values.shape` as function arguments (you can refer to python tutorials for more information). It is the same as
> 
> ```
> depth_values = depth_values.view(depth_values.shape[0], depth_values.shape[1], 1, 1)  # only when len(depth_values.shape) == 2
> ```

Thank you ~  It works!   And I want to konw whether the following code can replace this line?
# p: probability volume [B, D, H, W]
# depth_values: discrete depth values [B, D]
def depth_regression(p, depth_values):
    #depth_values = torch.reshape(depth_values,(256))
    depth_values = depth_values.cpu().numpy()
    start = depth_values[0][0]
    end = depth_values[0][-1]
    interval = (end - start) / 256
    disp = Variable(torch.Tensor(np.reshape(np.array(np.arange(start,end,interval)),[1,256,1,1])).cuda(),     requires_grad=False)
    disp = disp.repeat(p.size()[0],1,p.size()[2],p.size()[3])
    #print('depth_value ', depth_values.shape)
    depth = torch.sum(p * disp, 1)
    
    return depth

**Comment by xy-guo** [comment]
I'm not sure. You can check by yourself.
