### ISSUE TITLE
The correct metrics

### ISSUE THREAD

**Issue by kwea123** [xy-guo/MVSNet_pytorch#12]
I ran the evaluation code using your pretrained model.
The correct metrics should be the following: (I added the last row)
|   | Acc. | Comp. | Overall |
| --- | --- | --- | --- |
| MVSNet(D=256) | 0.396 | 0.527 | 0.462 |
| Your readme | 0.4492 | 0.3796 | 0.4144 |
| **Your pretrained** | 0.5229 | 0.4514 | 0.4871 |

which is slightly worse than original MVSNet, and that is reasonable because you use smaller `D=192`.
I used the same evaluation code to evaluate [RMVSNet](https://github.com/YoYo000/MVSNet) and his result is consistent with his provided model, so the evaluation code has no problem.

Could you explain how you get the numbers in the readme, otherwise it seems misleading that smaller D produces better result.

**Comment by kwea123** [comment]
I feel sorry, my evaluation is done in resolution 1152x864 because of insufficient memory. Is your metrics done in resolution 1600x1184 then?

**Comment by whubaichuan** [comment]
@kwea123 The code here uses 1600x1184. Maybe there are some differences in the fusion code. The original MVSNet uses fusibile to fuse all of the depth. But the fusion code here needs to be improved.

**Comment by whubaichuan** [comment]
@kwea123  
您好，最近遇到一个问题：关于mvsnet中D=192和D=256时，overall的值到底是多少。

第一，基于上所有published paper中，当D=256时，overall=0.462，这个问题不大。

第二，但是当D=192时，却大不一样：
a. 在这里提到overall=0.482, 但是它的这个仓库里说是0.414。
b. 在[cascade mvsnet ](https://paperswithcode.com/paper/cascade-cost-volume-for-high-resolution-multi) 和[point-mvs  ](https://paperswithcode.com/paper/point-based-multi-view-stereo-network)和若干其余论文中，overall=0.551。
 c. 在[mvs2](https://paperswithcode.com/paper/mvs2-deep-unsupervised-multi-view-stereo-with)  和 [unsup_mvs](https://paperswithcode.com/paper/learning-unsupervised-multi-view-stereopsis) 中，overall=0.592.



请问当D=192时，overall到底应该如何选择呢？

**Comment by kwea123** [comment]
跟resolution跟D有關吧，我測的是1152x864所以比這裡寫的0.414要差，它的結果應該是1600x1184的。
據我看，cascade是抄point mvs的結果，其他論文應該也是互抄，而point mvs裡提到這個數字是1152x864x192的結果，這個應該可信。
在unsupervised的兩篇論文中，training details中有提到resolution是640x512，所以他們的結果應該是640x512x192的。

結論：看你要比較哪個resolution就用哪個數字
有些論文抄數字會抄錯，所以最好多方比較... 另外確認一下overall是不是等於(acc+comp)/2，如果不是就是抄錯了

**Comment by whubaichuan** [comment]
@kwea123 嗯嗯，你跑出来的0.487和point mvs的0.551应该是相同的resolution, 怎么结果会有比较大的差别呢？

**Comment by kwea123** [comment]
可能因为这个训练得epoch比较长吧，这里是16原文是6
