### ISSUE TITLE
can't find pfm in eval.py

### ISSUE THREAD

**Issue by agenthong** [xy-guo/MVSNet_pytorch#13]
When I run eval.sh, an error occurs:
 No such file or directory: './outputs/scan1/depth_est/00000000.pfm'
I'm wondering is this pfm a result of eval.py? So I don't need to prepare this file.
Why it can't find this file?

**Comment by jeck-Linsec** [comment]
How did you deal with that?

**Comment by kk6398** [comment]
How did you deal with that?
