### ISSUE TITLE
Some problem about Evaluation Metrics.

### ISSUE THREAD

**Issue by StriveZs** [xy-guo/MVSNet_pytorch#26]
![image](https://user-images.githubusercontent.com/28866063/129169270-3d2c512f-364f-4936-a42b-0edec5ffc015.png)

Hello, I'm a freshman in this field, recently, I can run mvset_pytorch successfully, but when use the eval.py to fuse the depth maps and get the point cloud.ply files, but I don't know how to get above three metrics.

Are there some current software can evaluate these? Please tell how to get these three metrics.

**Comment by LiYaolab** [comment]
Hello, has your problem been solved? I have the same problem as you

**Comment by StriveZs** [comment]
Hi, this is Zander, I have solved this problem. May be you can the evaluation code in [Sample Set](http://roboimagedata.compute.dtu.dk/?page_id=36). Hope it can help you.

**Comment by LiYaolab** [comment]
OK, thanks. I'll have a look
