### ISSUE TITLE
Number of epoch

### ISSUE THREAD

**Issue by gxd1994** [xy-guo/MVSNet_pytorch#4]
why using 16?  origin using 6 epoch

**Comment by xy-guo** [comment]
I did not tried 6 epoch, but I think you may have a try to see the performance.

**Comment by gxd1994** [comment]
ok, thx

**Comment by XYZ-qiyh** [comment]
Hello @gxd1994 
Have you tried to train the netword using 6 epochs??
How does the number of Epochs influence the performance?
