### ISSUE TITLE
Does your test loss decline regularly?

### ISSUE THREAD

**Issue by yhw-yhw** [xy-guo/MVSNet_pytorch#6]
![image](https://user-images.githubusercontent.com/13210637/64922500-871efd00-d802-11e9-87e5-f763b32d0d5f.png)
I have re-train your model using the same setting as yours, and I test it for evaluating the depth map error on test dataset. 
I find out your depth map error is 8~9 using your provided model or re-trained model,  but the original MVSNet depth map error is only 4~5. 
Through the visualization of tensorboard, it seems that your model does not train well.

**Comment by yhw-yhw** [comment]
I have re-train your model using the same setting as yours, and I test it for evaluating the depth map error on test dataset.
I find out your depth map error is from 8 to 9 using your provided model or re-trained model, but the original MVSNet depth map error is only 45.
Through the visualization of tensorboard, it seems that your model does not train well.

**Comment by yhw-yhw** [comment]
I have re-train your model using the same setting as yours, and I test it for evaluating the depth map error on test dataset.
I find out your depth map error is from 8 to 9 using your provided model or re-trained model, but the original MVSNet depth map error is about 4 to 5.
Through the visualization of tensorboard, it seems that your model does not train well.

**Comment by xy-guo** [comment]
Sorry that I don't have much time to verify your problem. Maybe because of the pytorch verison? I used 0.4.1 for this code.

**Comment by XYZ-qiyh** [comment]
@yhw-yhw Hello, I have the same problem as you. Have you solved this problem? The testing loss is confusing.
![image](https://user-images.githubusercontent.com/45621782/71759499-d8094d00-2ee8-11ea-89b9-d0e4d1c89a32.png)

**Comment by yhw-yhw** [comment]
Cause the differences between this validation code and the original code,  I remember that one is depth range constraint, the other is the different dataset's number. You can compare this validation code carefully with the original validation code.

**Comment by whubaichuan** [comment]
@yhw-yhw what's the validation code and the original version?
