### ISSUE TITLE
Does deepthmap need to upsample when do evaluation?

### ISSUE THREAD

**Issue by gxd1994** [xy-guo/MVSNet_pytorch#7]
Hi, when i do evalution, the results are 2.21(acc)/1.56(comp)
the size of  depthmap is the 1/4 of the input image, Is this the reason?
Does deepthmap need to upsample when do evaluation?

**Comment by xy-guo** [comment]
Can you get the same result with my released model?

**Comment by gxd1994** [comment]
yes
