### ISSUE TITLE
Where is your test.sh

### ISSUE THREAD

**Issue by phongnhhn92** [xy-guo/MVSNet_pytorch#9]
Hello, I am trying to run test.sh using your provided pretrained model.
I cant find it anywhere,please help !

**Comment by whubaichuan** [comment]
@phongnhhn92 @xy-guo The test.sh is available. Looking forward to your reply.

**Comment by whubaichuan** [comment]
@phongnhhn92 I think test.sh have been fused into eval.sh

**Comment by phongnhhn92** [comment]
> @phongnhhn92 I think test.sh have been fused into eval.sh

Thanks! I will check it out. I will close the issue first and check back later when I have time.
